//
// EntitySearchQueryAllOfCreatedTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EntitySearchQueryAllOfCreatedTime: Codable, JSONEncodable, Hashable {
    case typeSearchQueryRangeOfDateTime(SearchQueryRangeOfDateTime)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSearchQueryRangeOfDateTime(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SearchQueryRangeOfDateTime.self) {
            self = .typeSearchQueryRangeOfDateTime(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of EntitySearchQueryAllOfCreatedTime"))
        }
    }
}

