//
// GeoCoordinates.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeoCoordinates: Codable, JSONEncodable, Hashable {

    public var lng: Double?
    public var lat: Double?

    public init(lng: Double? = nil, lat: Double? = nil) {
        self.lng = lng
        self.lat = lat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lng
        case lat
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lng, forKey: .lng)
        try container.encodeIfPresent(lat, forKey: .lat)
    }
}

