//
// ShinyFlakeStripeCardRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShinyFlakeStripeCardRequest: Codable, JSONEncodable, Hashable {

    static let numberRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let cvcRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var number: String
    public var expMonth: Int64
    public var expYear: Int64
    public var cvc: String

    public init(number: String, expMonth: Int64, expYear: Int64, cvc: String) {
        self.number = number
        self.expMonth = expMonth
        self.expYear = expYear
        self.cvc = cvc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case expMonth
        case expYear
        case cvc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(number, forKey: .number)
        try container.encode(expMonth, forKey: .expMonth)
        try container.encode(expYear, forKey: .expYear)
        try container.encode(cvc, forKey: .cvc)
    }
}

