//
// UserProfileActivity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfileActivity: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var totalDistance: Double?
    public var maxSpeed: Double?
    public var minSpeed: Double?
    public var maxAltitude: Double?
    public var minAltitude: Double?
    public var country: String?
    public var city: String?
    public var activitiesNumber: Int?
    public var profile: UserProfileActivityAllOfProfile?

    public init(id: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, totalDistance: Double? = nil, maxSpeed: Double? = nil, minSpeed: Double? = nil, maxAltitude: Double? = nil, minAltitude: Double? = nil, country: String? = nil, city: String? = nil, activitiesNumber: Int? = nil, profile: UserProfileActivityAllOfProfile? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.totalDistance = totalDistance
        self.maxSpeed = maxSpeed
        self.minSpeed = minSpeed
        self.maxAltitude = maxAltitude
        self.minAltitude = minAltitude
        self.country = country
        self.city = city
        self.activitiesNumber = activitiesNumber
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case updatedAt
        case totalDistance
        case maxSpeed
        case minSpeed
        case maxAltitude
        case minAltitude
        case country
        case city
        case activitiesNumber
        case profile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(totalDistance, forKey: .totalDistance)
        try container.encodeIfPresent(maxSpeed, forKey: .maxSpeed)
        try container.encodeIfPresent(minSpeed, forKey: .minSpeed)
        try container.encodeIfPresent(maxAltitude, forKey: .maxAltitude)
        try container.encodeIfPresent(minAltitude, forKey: .minAltitude)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(activitiesNumber, forKey: .activitiesNumber)
        try container.encodeIfPresent(profile, forKey: .profile)
    }
}

