//
// UserBookingModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserBookingModel: Codable, JSONEncodable, Hashable {

    public var start: Date
    public var end: Date
    public var couponCode: String?
    public var payAmount: Float
    public var creditCard: UserBookingModelCreditCard?

    public init(start: Date, end: Date, couponCode: String? = nil, payAmount: Float, creditCard: UserBookingModelCreditCard? = nil) {
        self.start = start
        self.end = end
        self.couponCode = couponCode
        self.payAmount = payAmount
        self.creditCard = creditCard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case start
        case end
        case couponCode
        case payAmount
        case creditCard
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(start, forKey: .start)
        try container.encode(end, forKey: .end)
        try container.encodeIfPresent(couponCode, forKey: .couponCode)
        try container.encode(payAmount, forKey: .payAmount)
        try container.encodeIfPresent(creditCard, forKey: .creditCard)
    }
}

