//
// UserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfile: Codable, JSONEncodable, Hashable {

    static let titleRule = StringRule(minLength: 0, maxLength: 45, pattern: nil)
    static let photoIdRule = StringRule(minLength: 0, maxLength: 50, pattern: nil)
    public var firstName: String?
    public var lastName: String?
    public var title: String?
    public var photoId: String?

    public init(firstName: String? = nil, lastName: String? = nil, title: String? = nil, photoId: String? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.title = title
        self.photoId = photoId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case title
        case photoId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(photoId, forKey: .photoId)
    }
}

