//
// UserCredential.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserCredential: Codable, JSONEncodable, Hashable {

    public var persistent: Bool?

    public init(persistent: Bool? = nil) {
        self.persistent = persistent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case persistent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(persistent, forKey: .persistent)
    }
}

