//
// UserModelAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserModelAllOf: Codable, JSONEncodable, Hashable {

    public var role: UserRole?
    public var secret: String?
    public var title: String?
    public var password: String?

    public init(role: UserRole? = nil, secret: String? = nil, title: String? = nil, password: String? = nil) {
        self.role = role
        self.secret = secret
        self.title = title
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case secret
        case title
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

