//
// UserBookingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserBookingResponse: Codable, JSONEncodable, Hashable {

    public var bookingId: String?
    public var redirectUrl: String?

    public init(bookingId: String? = nil, redirectUrl: String? = nil) {
        self.bookingId = bookingId
        self.redirectUrl = redirectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bookingId
        case redirectUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bookingId, forKey: .bookingId)
        try container.encodeIfPresent(redirectUrl, forKey: .redirectUrl)
    }
}

