//
// UserEntityPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserEntityPermissions: Codable, JSONEncodable, Hashable {

    public var read: Bool?
    public var update: Bool?

    public init(read: Bool? = nil, update: Bool? = nil) {
        self.read = read
        self.update = update
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case read
        case update
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(read, forKey: .read)
        try container.encodeIfPresent(update, forKey: .update)
    }
}

