//
// UserBookedDates.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserBookedDates: Codable, JSONEncodable, Hashable {

    public var bookedDates: [ValueTupleOfDateTimeAndDateTime]?

    public init(bookedDates: [ValueTupleOfDateTimeAndDateTime]? = nil) {
        self.bookedDates = bookedDates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bookedDates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bookedDates, forKey: .bookedDates)
    }
}

