//
// UserRegistrationModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserUpdateDeviceId: Codable, JSONEncodable, Hashable {

    
    public var deviceId: String
    public var deviceType: UserDeviceType

    public init(deviceId: String, deviceType: UserDeviceType) {
        self.deviceId = deviceId
        self.deviceType = deviceType
        
        
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        
        case deviceId
        case deviceType
        
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(deviceType, forKey: .deviceType)
        
    }
    
}

public enum UserDeviceType: Int, Codable, CaseIterable {
    case Android = 0 // android
    case Ios = 1 // ios
    case Desktop = 2 // desktop
}
